### ISSUE TITLE
messages are duplicating

### ISSUE THREAD

**Issue by andrewMacmurray** [sockinit/sockinit#43]
Not sure why this is happening but had my window open for a while and keep seeing the only message I posted repeated about 10 times

**Comment by katbow** [comment]
It seems to happen every time someone new joins the chat - it duplicates the last few messages for everyone.

**Comment by jay-meister** [comment]
think it is fixed now @andrewMacmurray

**Comment by jay-meister** [comment]
https://sockinit.herokuapp.com/chatting/andrew

**Comment by andrewMacmurray** [comment]
:+1:
